apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecurl
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111111111:role/replace-with-your-value
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubecurl-pod-reader-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: kubecurl
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecurl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecurl
  template:
    metadata:
      labels:
        app: kubecurl
    spec:
      serviceAccountName: kubecurl
      containers:
        - name: kubecurl
          image: lanceapps/kubecurl:1.0.0
          resources:
            requests:
              cpu: '0.25'
              memory: '0.5G'
            limits:
              cpu: '0.25'
              memory: '0.5G'
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kubecurl
  annotations:
    kubernetes.io/aws-load-balancer-type: external
    kubernetes.io/aws-load-balancer-scheme: internet-facing
    kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: kubecurl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  type: LoadBalancer
